<?php
use Dompdf\Dompdf;
use Dompdf\Options;

function generate_transcript($student, $results, $cgpa) {
    // Initialize Dompdf
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isPhpEnabled', true);
    
    $dompdf = new Dompdf($options);
    
    // Format date
    $date = date('F d, Y');
    
    // Calculate totals
    $total_credit_units = 0;
    $total_grade_points = 0;
    
    // Generate HTML for the transcript
    $html = <<<HTML
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {
                font-family: 'Helvetica', sans-serif;
                margin: 0;
                padding: 20px;
                background-color: white;
            }
            .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid #2563EB;
                padding-bottom: 20px;
            }
            .title {
                font-size: 24px;
                color: #2563EB;
                margin-bottom: 10px;
                font-weight: bold;
            }
            .student-info {
                margin-bottom: 30px;
            }
            .student-info p {
                margin: 5px 0;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 30px;
            }
            th, td {
                border: 1px solid #E5E7EB;
                padding: 8px;
                text-align: left;
                font-size: 12px;
            }
            th {
                background-color: #F3F4F6;
                font-weight: bold;
            }
            .summary {
                margin-top: 30px;
                padding: 15px;
                background-color: #F3F4F6;
                border-radius: 5px;
            }
            .cgpa {
                font-size: 18px;
                color: #2563EB;
                font-weight: bold;
            }
            .footer {
                margin-top: 50px;
                text-align: center;
                font-size: 12px;
                color: #6B7280;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="title">GRCC CBT System</div>
            <div>Official Academic Transcript</div>
        </div>
        
        <div class="student-info">
            <p><strong>Student Name:</strong> {$student['name']}</p>
            <p><strong>Student ID:</strong> {$student['id']}</p>
            <p><strong>Date Generated:</strong> {$date}</p>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Credit Units</th>
                    <th>Score</th>
                    <th>Grade</th>
                    <th>Grade Point</th>
                </tr>
            </thead>
            <tbody>
    HTML;
    
    foreach ($results as $result) {
        $grade_point = get_grade_point($result['grade']);
        $total_credit_units += $result['credit_units'];
        $total_grade_points += ($grade_point * $result['credit_units']);
        
        $html .= <<<HTML
                <tr>
                    <td>{$result['course_code']}</td>
                    <td>{$result['course_name']}</td>
                    <td>{$result['credit_units']}</td>
                    <td>{$result['score']}%</td>
                    <td>{$result['grade']}</td>
                    <td>{$grade_point}</td>
                </tr>
        HTML;
    }
    
    $html .= <<<HTML
            </tbody>
        </table>
        
        <div class="summary">
            <p><strong>Total Credit Units:</strong> {$total_credit_units}</p>
            <p><strong>Total Grade Points:</strong> {$total_grade_points}</p>
            <p class="cgpa">Cumulative GPA (CGPA): {$cgpa}</p>
        </div>
        
        <div class="footer">
            <p>This is an official transcript generated by GRCC CBT System</p>
            <p>Date Generated: {$date}</p>
        </div>
    </body>
    </html>
    HTML;
    
    // Load HTML into Dompdf
    $dompdf->loadHtml($html);
    
    // Set paper size
    $dompdf->setPaper('A4', 'portrait');
    
    // Render the PDF
    $dompdf->render();
    
    // Generate a unique filename
    $filename = sprintf(
        'transcript_%s_%s.pdf',
        sanitize_filename($student['name']),
        date('Y-m-d')
    );
    
    // Save to storage directory
    $transcript_path = TRANSCRIPTS_DIR . '/' . $filename;
    file_put_contents($transcript_path, $dompdf->output());
    
    // Output the PDF to browser
    $dompdf->stream($filename, array('Attachment' => true));
}

// Helper function to get grade point
function get_grade_point($grade) {
    $grade_points = [
        'A' => 4.0,
        'B' => 3.0,
        'C' => 2.0,
        'D' => 1.0,
        'F' => 0.0
    ];
    return $grade_points[$grade] ?? 0;
}

// Helper function to sanitize filename
function sanitize_filename($string) {
    return preg_replace('/[^a-zA-Z0-9_-]/', '_', strtolower($string));
}